/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLS.DB;
import java.sql.ResultSet;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASHANSOFT
 */
public class Numbers extends javax.swing.JPanel {

    /**
     * Creates new form Numbers
     */
    public Numbers() {
        initComponents();
    }
    
    public static int q = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B9.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(860, 530, 150, 142);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B1.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3);
        jLabel3.setBounds(130, 220, 150, 142);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B2.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        add(jLabel4);
        jLabel4.setBounds(380, 220, 150, 142);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B3.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5);
        jLabel5.setBounds(620, 220, 150, 142);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B4.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        add(jLabel6);
        jLabel6.setBounds(860, 220, 150, 142);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B10.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7);
        jLabel7.setBounds(1110, 530, 150, 142);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B8.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8);
        jLabel8.setBounds(620, 530, 150, 142);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B7.png"))); // NOI18N
        jLabel9.setText("jLabel2");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        add(jLabel9);
        jLabel9.setBounds(380, 530, 150, 142);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B6.png"))); // NOI18N
        jLabel10.setText("jLabel2");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        add(jLabel10);
        jLabel10.setBounds(130, 530, 150, 142);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Numbers/B5.png"))); // NOI18N
        jLabel11.setText("jLabel2");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        add(jLabel11);
        jLabel11.setBounds(1110, 220, 150, 142);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Bacground/Numbers.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, -10, 1370, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+1+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+1+"'");
                        q = 1;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+2+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+2+"'");
                        q = 2;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+3+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+3+"'");
                        q = 3;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+4+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+4+"'");
                        q = 4;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+5+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+5+"'");
                        q = 5;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+6+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+6+"'");
                        q = 6;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+7+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+7+"'");
                        q = 7;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+8+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+8+"'");
                        q = 8;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+9+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+9+"'");
                        q = 9;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        try {
            ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+10+"'");
            while (rs.next()){
                if (rs.getString("State").equals("Not")) {
                    int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        DB.getCon().createStatement().executeUpdate("UPDATE number SET State = '"+"Yes"+"' WHERE Number = '"+10+"'");
                        q = 10;
                        Base_Form.x = 0;
                        Base_Form.Base_Panel.removeAll();
                        GroupLayout gl=new GroupLayout(Base_Form.Base_Panel);
                        Base_Form.Base_Panel.setLayout(gl);
                        Questions que = new Questions();
                        gl.setHorizontalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                        gl.setVerticalGroup(gl.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(que, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange

        int i = 0;
        String[] s = new String[10];
        ImageIcon image = new ImageIcon();
        while (i <10) {
            i+=1;
            try {
                ResultSet rs = DB.getCon().createStatement().executeQuery("SELECT State FROM number WHERE Number = '"+i+"'");
                while (rs.next()){
                    if (rs.getString("State").equals("Not")) {
                        s[i-1] = "Not";
                    }else{
                        s[i-1] = "Yes";
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        if (s[0].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B1.png");
            jLabel3.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R1.png");
            jLabel3.setIcon(image);
        }
        if (s[1].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B2.png");
            jLabel4.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R2.png");
            jLabel4.setIcon(image);
        }
        if (s[2].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B3.png");
            jLabel5.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R3.png");
            jLabel5.setIcon(image);
        }
        if (s[3].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B4.png");
            jLabel6.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R4.png");
            jLabel6.setIcon(image);
        }
        if (s[4].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B5.png");
            jLabel11.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R5.png");
            jLabel11.setIcon(image);
        }
        if (s[5].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B6.png");
            jLabel10.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R6.png");
            jLabel10.setIcon(image);
        }
        if (s[6].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B7.png");
            jLabel9.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R7.png");
            jLabel9.setIcon(image);
        }
        if (s[7].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B8.png");
            jLabel8.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R8.png");
            jLabel8.setIcon(image);
        }
        if (s[8].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B9.png");
            jLabel2.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R9.png");
            jLabel2.setIcon(image);
        }
        if (s[9].equals("Not")) {
            image = new ImageIcon("C:\\Photoshop\\Number\\Blue\\B10.png");
            jLabel7.setIcon(image);
        }else{
            image = new ImageIcon("C:\\Photoshop\\Number\\Red\\R10.png");
            jLabel7.setIcon(image);
        }
    }//GEN-LAST:event_formPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
