/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLS.DB;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASHANSOFT
 */
public class Questions extends javax.swing.JPanel {

    /**
     * Creates new form Questions
     */
    public Questions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(null);
        add(jLabel2);
        jLabel2.setBounds(1170, 20, 150, 142);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Bacground/1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(170, 210, 1040, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Index/C.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(210, 590, 50, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Index/A.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(210, 430, 50, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Index/B.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(710, 430, 50, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Index/D.png"))); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(710, 590, 50, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Index/1.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(770, 580, 380, 54);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Index/1.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(280, 580, 380, 54);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Index/1.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(770, 420, 380, 54);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Index/1.png"))); // NOI18N
        add(jLabel12);
        jLabel12.setBounds(270, 420, 380, 54);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Bacground/Fifty.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        add(jLabel13);
        jLabel13.setBounds(10, 10, 154, 71);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Bacground/Questions.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange

        Questions.jLabel3.setVisible(false);
        Questions.jLabel12.setVisible(false);
        Questions.jLabel11.setVisible(false);
        Questions.jLabel7.setVisible(false);
        Questions.jLabel6.setVisible(false);
        Questions.jLabel8.setVisible(false);
        Questions.jLabel9.setVisible(false);
        Questions.jLabel10.setVisible(false);
        Questions.jLabel4.setVisible(false);
        Questions.jLabel13.setVisible(false);
    }//GEN-LAST:event_formPropertyChange

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked


        
        int i = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            if (Numbers.q == 1) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }
            }else if (Numbers.q == 2) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }
            }else if (Numbers.q == 3) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }
            }else if (Numbers.q == 4) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }
            }else if (Numbers.q == 5) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }
            }else if (Numbers.q == 6) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }
            }else if (Numbers.q == 7) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }
            }else if (Numbers.q == 8) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }
            }else if (Numbers.q == 9) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }
            }else if (Numbers.q == 10) {
                if (Base_Form.qq == 1) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 2) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }else if (Base_Form.qq == 3) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 4) {
                    Questions.jLabel12.setVisible(false);
                    Questions.jLabel6.setVisible(false);
                    Questions.jLabel8.setVisible(false);
                    Questions.jLabel10.setVisible(false);
                }else if (Base_Form.qq == 5) {
                    Questions.jLabel11.setVisible(false);
                    Questions.jLabel7.setVisible(false);
                    Questions.jLabel9.setVisible(false);
                    Questions.jLabel4.setVisible(false);
                }
            }
            ImageIcon image = new ImageIcon("C:\\Photoshop\\Timer\\Timer 2.gif");
            Questions.jLabel2.setIcon(image);
            timer();
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void set_visible() {
        Questions.jLabel3.setVisible(true);
        Questions.jLabel12.setVisible(true);
        Questions.jLabel11.setVisible(true);
        Questions.jLabel7.setVisible(true);
        Questions.jLabel6.setVisible(true);
        Questions.jLabel8.setVisible(true);
        Questions.jLabel9.setVisible(true);
        Questions.jLabel10.setVisible(true);
        Questions.jLabel4.setVisible(true);
        Questions.jLabel13.setVisible(true);
    }
    private void timer() {
        
        jLabel2.setVisible(true);
        new Thread(new Runnable() {

            @Override
            public void run() {
                int ii = 0;
                for(int i = 0; i < 8; i++){
                    try {
                        Thread.sleep(1000);

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                Toolkit.getDefaultToolkit().beep();
                jLabel2.setIcon(null);
                Questions.jLabel2.setVisible(false);
            }
        }).start();
    }
}
